# Generated by Django 3.1.3 on 2021-02-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auswertung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('datei', models.FileField(blank=True, null=True, upload_to='')),
                ('handout', models.BooleanField(default=False)),
                ('uniqueDir', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Uploaded File 2',
                'verbose_name_plural': 'Uploaded Files 2',
            },
        ),
        migrations.CreateModel(
            name='crawlURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=400, null=True)),
                ('crawlTiefe', models.PositiveIntegerField(blank=True, default=2, null=True)),
                ('haendler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auswertung.haendler')),
            ],
            options={
                'verbose_name': 'Crawl URL',
                'verbose_name_plural': 'Crawl URLs',
            },
        ),
    ]
